# Generated by Django 5.0 on 2024-04-15 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="title_tag",
            field=models.CharField(max_length=255),
        ),
    ]
