# Generated by Django 4.2.11 on 2024-04-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog", "0002_post_post_date_alter_post_title_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="coding", max_length=255),
        ),
    ]
